# goal definition
std_msgs/Header header
int64[] apriltag_ids
---

# result: list of cubes' positions
std_msgs/Header header
geometry_msgs/PoseStamped[] aprilTags_poses
---
# feedback
std_msgs/Header header
string robot_status
