base_local_planner_params:

  lethal_cost: 253  # Default value, change if needed
  neutral_cost: 50  # Default value, adjust as per your requirements
  cost_factor: 3.0  # Default value, modify for custom tuning
